kind: Deployment
apiVersion: apps/v1
metadata:
  name: prow-pipeline
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prow-pipeline
  template:
    metadata:
      labels:
        app: prow-pipeline
    spec:
      serviceAccountName: prow-pipeline
      containers:
      - name: pipeline
        image: gcr.io/k8s-prow/pipeline:v20221123-4b1eb2a191
        args:
        - --all-contexts
        - --config=/etc/prow-config/config.yaml
        env:
        # Use KUBECONFIG envvar rather than --kubeconfig flag in order to provide multiple configs to merge.
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config:/etc/build-intel-istio/kubeconfig"
        volumeMounts:
        - mountPath: /etc/build-intel-istio
          name: build-intel-istio
          readOnly: true
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/prow-config
          name: prow-config
          readOnly: true
      volumes:
      - name: build-intel-istio
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-intel-istio
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: prow-config
        configMap:
          name: config
